# Generated by Django 3.1 on 2020-08-17 02:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEventCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(blank=True, choices=[('A Survey in Western Literature I', 'A Survey in Western Literature I'), ('A Survey in Western Literature II', 'A Survey in Western Literature II'), ('A Survey in American Literature I', 'A Survey in American Literature I'), ('A Survey in European Literature I', 'A Survey in European Literature I')], help_text='Select which collection to this content is under ', max_length=100, null=True)),
                ('collection_event', models.CharField(blank=True, choices=[('ASWL1_E1', 'ASWL1_E1'), ('ASWL1_E2', 'ASWL1_E2'), ('ASWL1_E3', 'ASWL1_E3'), ('ASWL1_E4', 'ASWL1_E4'), ('ASWL1_E5', 'ASWL1_E5'), ('ASWL1_E6', 'ASWL1_E6'), ('ASWL1_E7', 'ASWL1_E7'), ('ASWL2_E1', 'ASWL2_E1'), ('ASWL2_E2', 'ASWL2_E2'), ('ASWL2_E3', 'ASWL2_E3'), ('ASWL2_E4', 'ASWL2_E4'), ('ASWL2_E5', 'ASWL2_E5'), ('ASWL2_E6', 'ASWL2_E6'), ('ASWL2_E7', 'ASWL2_E7'), ('ASAL1_E1', 'ASAL1_E1'), ('ASAL1_E2', 'ASAL1_E2'), ('ASAL1_E3', 'ASAL1_E3'), ('ASAL1_E4', 'ASAL1_E4'), ('ASAL1_E5', 'ASAL1_E5'), ('ASAL1_E6', 'ASAL1_E6'), ('ASAL1_E7', 'ASAL1_E7'), ('ASEL1_E1', 'ASEL1_E1'), ('ASEL1_E2', 'ASEL1_E2'), ('ASEL1_E3', 'ASEL1_E3'), ('ASEL1_E4', 'ASEL1_E4'), ('ASEL1_E5', 'ASEL1_E5'), ('ASEL1_E6', 'ASEL1_E6'), ('ASEL1_E7', 'ASEL1_E7')], help_text='Select which event (e1 - e7) this content is under ', max_length=10, null=True)),
                ('event_title', models.CharField(blank=True, help_text='Enter the title of your event.', max_length=120, null=True)),
                ('event_descriptor', models.TextField(blank=True, help_text='Enter a one-sentence description of the content and goal of your event.', null=True)),
                ('quotation', models.TextField(blank=True, help_text='Enter a quotation that exemplifies this event.', null=True)),
                ('quotation_author', models.CharField(blank=True, help_text='Enter the author or source of the quotation.', max_length=50, null=True)),
                ('quote_source', wagtail.core.fields.RichTextField(blank=True, help_text='Enter the citation for the source of this quotation.', null=True)),
                ('author_image', models.ForeignKey(blank=True, help_text='Upload an image for the author of the quotation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Event Overview',
                'verbose_name_plural': 'Event Overviews',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
