# Generated by Django 3.1 on 2020-08-17 02:55

from django.db import migrations, models
import django.db.models.deletion
import readings.models
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('categories', '0001_initial'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryFocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', wagtail.core.fields.StreamField([('Keywords', readings.models.Keywords())], blank=True, help_text='Enter key terms and concepts related to this Primary Reading', null=True)),
                ('author_dob', models.CharField(blank=True, help_text='Enter the author’s date of birth and date of death.', max_length=100, null=True)),
                ('translator_name', models.CharField(blank=True, help_text='Enter the full name of the translator.', max_length=200, null=True)),
                ('author_first_name', models.CharField(blank=True, help_text='Enter the author’s first name.', max_length=50, null=True)),
                ('author_last_name', models.CharField(blank=True, help_text='Enter the author’s last name.', max_length=50, null=True)),
                ('title_major', models.CharField(blank=True, help_text='Enter the full title of the major work.', max_length=100, null=True)),
                ('synopsis', wagtail.core.fields.RichTextField(blank=True, help_text='Enter a synopsis for the major work with at least one secondary source reference.', null=True)),
                ('purchase_link', models.CharField(blank=True, help_text='Enter a link to where the work can be ordered.', max_length=500, null=True)),
                ('level_ability', models.CharField(blank=True, choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], help_text='Select the reading level of the major work.', max_length=20, null=True)),
                ('page_count', models.IntegerField(blank=True, help_text='Enter the number of pages in the major work.', null=True)),
                ('source', wagtail.core.fields.RichTextField(blank=True, help_text='Enter, MLA source of the work', null=True)),
                ('book_image', models.ForeignKey(blank=True, help_text='Upload an image for the book cover.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('event_collection', models.ForeignKey(blank=True, help_text='Enter even collection this to which this reading belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.categoryeventcollection')),
                ('reading_category', models.ForeignKey(blank=True, help_text='Select or create a reading category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='categories.readingcategory')),
            ],
            options={
                'verbose_name': 'Primary Focus',
                'verbose_name_plural': 'Primary Focuses',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='FurtherExplorations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', wagtail.core.fields.StreamField([('Keywords', readings.models.Keywords())], blank=True, help_text='Enter key terms and concepts related to this resource.', null=True)),
                ('author_dob', models.CharField(blank=True, help_text="Enter resource author's date of birth.", max_length=100, null=True)),
                ('author_first_name', models.CharField(blank=True, help_text="Enter resource author's first name.", max_length=50, null=True)),
                ('author_last_name', models.CharField(blank=True, help_text="Enter resource author's last name.", max_length=50, null=True)),
                ('title_minor', models.CharField(blank=True, help_text='Enter the full title of the minor work.', max_length=100, null=True)),
                ('translator_name', models.CharField(blank=True, help_text='Enter the full name of the translator.', max_length=200, null=True)),
                ('excerpt', wagtail.core.fields.RichTextField(blank=True, help_text='Enter an excerpt from the beginning of the minor work.', null=True)),
                ('source', wagtail.core.fields.RichTextField(blank=True, help_text='Enter, MLA source of the work', null=True)),
                ('event_collection', models.ForeignKey(blank=True, help_text='Select event to which this resource belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.categoryeventcollection')),
                ('reading_category', models.ForeignKey(blank=True, help_text='Enter the category of this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='categories.readingcategory')),
                ('resource_link', models.ForeignKey(blank=True, help_text="Enter resource's link.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'verbose_name': 'Further Exploration',
                'verbose_name_plural': 'Further Explorations',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
