# Generated by Django 3.1 on 2020-08-17 02:55

import assignment_types.models
from django.db import migrations, models
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(blank=True, choices=[('essential_category', 'essential_category'), ('analytic_category', 'analytic_category'), ('journalism_category', 'journalism_category'), ('realworld_category', 'realworld_category'), ('creative_category', 'creative_category'), ('internet_category', 'internet_category'), ('visual_category', 'visual_category'), ('poetry_category', 'poetry_category'), ('business_category', 'business_category')], help_text='Select the category type.', max_length=100, null=True)),
                ('title', models.CharField(blank=True, choices=[('Essential', 'Essential'), ('Analytic', 'Analytic'), ('Journalism', 'Journalism'), ('Real World', 'Real World'), ('Creative', 'Creative'), ('Internet', 'Internet'), ('Visual', 'Visual'), ('Poetry', 'Poetry'), ('Business and Technical', 'Business and Technical')], help_text='Select the type of feat.', max_length=100, null=True)),
                ('verb', models.CharField(blank=True, choices=[('compose', 'compose'), ('create', 'create'), ('craft', 'craft')], help_text='Select the verb you for this feat.', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Enter the description of the assignment type.', null=True)),
                ('feat', models.CharField(blank=True, help_text='Enter the assignment feat.', max_length=255, null=True)),
                ('topics', wagtail.core.fields.StreamField([('Topics', assignment_types.models.Topics())], blank=True, help_text='Enter any topics to explore', null=True)),
            ],
            options={
                'verbose_name': 'Assignment Type',
                'verbose_name_plural': 'Assignment Types',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
