# Generated by Django 3.1 on 2020-09-15 05:53

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlexis',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_lexis', to='user_lessons.userlesson'),
        ),
    ]
