# Generated by Django 3.1 on 2020-09-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_lessons', '0002_auto_20200915_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonexplorations',
            name='exploration_links',
        ),
        migrations.RemoveField(
            model_name='lessonexplorations',
            name='page',
        ),
        migrations.RemoveField(
            model_name='lessonextensions',
            name='extension_links',
        ),
        migrations.RemoveField(
            model_name='lessonextensions',
            name='page',
        ),
        migrations.RemoveField(
            model_name='lessongoals',
            name='goal_links',
        ),
        migrations.RemoveField(
            model_name='lessongoals',
            name='page',
        ),
        migrations.RemoveField(
            model_name='lessonlexis',
            name='lexis_links',
        ),
        migrations.RemoveField(
            model_name='lessonlexis',
            name='page',
        ),
        migrations.RemoveField(
            model_name='lessonperformances',
            name='page',
        ),
        migrations.RemoveField(
            model_name='lessonperformances',
            name='performance_links',
        ),
        migrations.RemoveField(
            model_name='lessonquestions',
            name='page',
        ),
        migrations.RemoveField(
            model_name='lessonquestions',
            name='question_links',
        ),
        migrations.RemoveField(
            model_name='userlesson',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='userlesson',
            name='event_collection',
        ),
        migrations.RemoveField(
            model_name='userlesson',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='userlesson',
            name='primary_reading',
        ),
        migrations.DeleteModel(
            name='ClassSubject',
        ),
        migrations.DeleteModel(
            name='LessonExplorations',
        ),
        migrations.DeleteModel(
            name='LessonExtensions',
        ),
        migrations.DeleteModel(
            name='LessonGoals',
        ),
        migrations.DeleteModel(
            name='LessonLexis',
        ),
        migrations.DeleteModel(
            name='LessonPerformances',
        ),
        migrations.DeleteModel(
            name='LessonQuestions',
        ),
        migrations.DeleteModel(
            name='UserLesson',
        ),
    ]
