# Generated by Django 3.1 on 2020-08-17 02:55

from django.db import migrations, models
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContinualGoalStandardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_type', models.CharField(help_text='Enter standard type for Continual Goal', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Goal Standard Type',
                'verbose_name_plural': 'Goal Standard Types',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ExtensionCommandType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(help_text='Enter the Extension command name such as define, read, identify, etc', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Extension Command',
                'verbose_name_plural': 'Extension Commands',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ReadingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Enter Category name such as poetry, novel, short stories, etc.', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Reading Category',
                'verbose_name_plural': 'Reading Categories',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
