# Generated by Django 3.1 on 2020-09-16 02:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(blank=True, choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], help_text='Select class grade level', max_length=100, null=True)),
                ('class_name', models.CharField(help_text='Enter the class title.', max_length=500)),
                ('class_description', models.TextField(blank=True, help_text='Enter the class description', null=True)),
                ('instructor', models.ForeignKey(help_text='Select user who is the teacher connected to this profile.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='teacher_profile.teacherprofile')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(help_text='Enter the lesson title.', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lesson_selections', models.TextField(blank=True, help_text='JSON Represention of lesson selections.', null=True)),
                ('class_name', models.ForeignKey(help_text='Select class to this profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_name_lesson', to='teacher_lessons.classsubject')),
                ('instructor', models.ForeignKey(blank=True, help_text='Select user who is the teacher who created the lesson.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile_lesson', to='teacher_profile.teacherprofile')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
