# Generated by Django 3.1 on 2020-09-16 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='class_name',
            field=models.ForeignKey(blank=True, help_text='Select class to this profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_name_lesson', to='teacher_lessons.classsubject'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='lesson_title',
            field=models.CharField(blank=True, help_text='Enter the lesson title.', max_length=500, null=True),
        ),
    ]
