# Generated by Django 3.1 on 2020-09-17 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_profile', '0001_initial'),
        ('teacher_lessons', '0003_auto_20200916_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlesson',
            name='class_name',
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Select user who is the teacher connected to this profile.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='teacher_profile.teacherprofile'),
        ),
    ]
