# Generated by Django 3.1 on 2020-09-25 02:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_lessons', '0004_auto_20200917_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
