# Generated by Django 3.1 on 2020-10-02 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_lessons', '0005_auto_20200925_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlesson',
            name='class_link',
            field=models.ForeignKey(blank=True, help_text='Select class to this profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_name_lesson', to='teacher_lessons.classsubject'),
        ),
        migrations.AddField(
            model_name='userlesson',
            name='lesson_description',
            field=models.TextField(blank=True, help_text='Enter the lesson description', null=True),
        ),
    ]
