# Generated by Django 3.1 on 2020-10-02 01:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_lessons', '0006_auto_20201002_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
