# Generated by Django 3.1 on 2020-10-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_lessons', '0007_auto_20201002_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='class_link',
            field=models.CharField(blank=True, help_text='Enter the lesson title.', max_length=500, null=True),
        ),
    ]
