# Generated by Django 3.1 on 2020-08-17 02:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinualGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(blank=True, help_text='Establish the goal that the students will be able to meet', max_length=100, null=True)),
                ('explanation', wagtail.core.fields.RichTextField(blank=True, help_text='Enter explanation on how to teach the goal.', null=True)),
                ('video_link', models.CharField(blank=True, help_text='Enter video link on how to teach the goal.', max_length=500, null=True)),
                ('standard_type', models.ForeignKey(blank=True, help_text='Select the standard this goal meets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='categories.continualgoalstandardtype')),
            ],
            options={
                'verbose_name': 'Continual Goal',
                'verbose_name_plural': 'Continual Goals',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
