# Generated by Django 3.1 on 2020-08-17 02:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, help_text='Enter the key question students should be able to answer by the end of the event.', max_length=100, null=True)),
                ('explanation', wagtail.core.fields.RichTextField(blank=True, help_text='Enter explanation on how to teach the question.', null=True)),
                ('video_link', models.CharField(blank=True, help_text='Enter video link on how to teach the question.', max_length=500, null=True)),
                ('event_collection', models.ForeignKey(blank=True, help_text='Enter collection to which this question belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.categoryeventcollection')),
            ],
            options={
                'verbose_name': 'Key Question',
                'verbose_name_plural': 'Key Questions',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
