# Generated by Django 3.1 on 2020-08-16 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, help_text='Enter the name of the learning institution.', max_length=100, null=True)),
                ('grade_level', models.CharField(blank=True, choices=[('K-5', 'K-5'), ('6-8', '6-8'), ('9-12', '9-12'), ('K-12', 'K-12'), ('K-8', 'K-8'), ('6-12', '6-12')], help_text='Enter the grade levels of the learning institution.', max_length=40)),
                ('subjects', models.TextField(blank=True, help_text='Enter the subjects taught at your learning institution.', null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Enter primary contact phone number at the learning institution.', max_length=200, null=True)),
                ('street_address', models.CharField(blank=True, help_text='Enter address of the learning institution.', max_length=200, null=True)),
                ('city', models.CharField(blank=True, help_text='Enter the city of the learning institution.', max_length=200, null=True)),
                ('postcode', models.CharField(blank=True, help_text='Enter the city of the learning institution.', max_length=200, null=True)),
                ('province', models.CharField(blank=True, help_text='Enter the province of the learning institution.', max_length=200, null=True)),
                ('country', models.CharField(blank=True, help_text='Enter the country of the learning institution.', max_length=200, null=True)),
                ('primary_contact', models.OneToOneField(blank=True, help_text='Enter primary user and contact at the learning institution.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School profile',
                'verbose_name_plural': 'School profiles',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
